version: '3.1'

services:

  db:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  adminer:
    image: adminer
    ports:
      - 8081:8080

  search:
    image: elasticsearch:8.11.1
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300